version: "3.8"
services:
    prometheus:
        image: prom/prometheus
        ports:
        - 9090:9090
        volumes:
        - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
        command: --config.file=/etc/prometheus/prometheus.yml
    grafana:
        image: grafana/grafana
        ports:
        - 3000:3000
    otel-collector:
        image: otel/opentelemetry-collector-contrib:0.97.0
        ports:
            - "1888:1888"   # pprof extension
            - "8888:8888"   # Prometheus metrics exposed by the collector
            - "8889:8889"   # Prometheus exporter metrics
            - "13133:13133" # health_check extension
            - "55679:55679" # zpages extension
            - "4317:4317"   # otlp receiver
            - "4318:4318"   # otlp receiver
        volumes:
        - ./otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
        command: --config=/etc/otel-collector-config.yaml
    jaeger:
        image: jaegertracing/all-in-one
        ports:
        - 4319:4318
        - 16686:16686
        environment:
        - COLLECTOR_OTLP_ENABLED=true
    postgres:
        image: postgres:latest
        ports:
        - 5432:5432
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres