receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"  # HTTP endpoint for OTLP (used by the Spring Boot application)
      grpc:
        endpoint: "0.0.0.0:4317"  # gRPC endpoint for OTLP

exporters:
  otlp/jaeger:
    endpoint: http://jaeger:4317
    tls:
      insecure: true


service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp/jaeger]