receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
  prometheus:
    config:
      scrape_configs:
        - job_name: 'otel-collector'
          scrape_interval: 10s
          static_configs:
            - targets: [ 'localhost:9090' ]

processors:
  batch:

exporters:
  logging:
    loglevel: debug
  otlphttp/jaeger:
    endpoint: http://jaeger:4318
  prometheus:
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ batch ]
      exporters: [ logging, otlphttp/jaeger ]
    metrics:
        receivers: [ otlp ]
        processors: [ batch ]
        exporters: [ logging, prometheus]
  telemetry:
    logs:
      level: debug